allow_cache: true
ap_dim_end: 29
ap_dim_start: 29
batch_max_steps: 16000
batch_size: 6
config: conf/arctic.uSFGAN_60.yaml
discriminator_grad_norm: 1
discriminator_optimizer_params:
  eps: 1.0e-06
  lr: 5.0e-05
  weight_decay: 0.0
discriminator_params:
  bias: true
  conv_channels: 64
  in_channels: 1
  kernel_size: 3
  layers: 10
  nonlinear_activation: LeakyReLU
  nonlinear_activation_params:
    negative_slope: 0.2
  out_channels: 1
  use_weight_norm: true
discriminator_scheduler_params:
  gamma: 0.5
  step_size: 200000
discriminator_train_start_steps: 100000
discriminator_type: PWGDiscriminator
distributed: false
eval_interval_steps: 1000
f0_cont: false
f0_dim_idx: 1
feat_type: world
fft_size: 1024
generator_grad_norm: 10
generator_optimizer_params:
  eps: 1.0e-06
  lr: 0.0001
  weight_decay: 0.0
generator_params:
  aux_channels: 29
  aux_context_window: 2
  blockAs:
  - 30
  - 0
  blockFs:
  - 0
  - 30
  cascade_modes:
  - 1
  - 1
  cycleAs:
  - 6
  - 0
  cycleFs:
  - 0
  - 3
  gate_channels: 128
  hop_size: 80
  in_channels: 1
  out_channels: 1
  residual_channels: 64
  sampling_rate: 16000
  skip_channels: 64
  upsample_params:
    upsample_scales:
    - 4
    - 2
    - 5
    - 2
generator_scheduler_params:
  gamma: 0.5
  step_size: 200000
generator_type: uSFGANGenerator
highpass_cutoff: 70
hop_size: 80
lambda_adv: 4.0
lambda_source: 1.0
log_interval_steps: 100
maxf0: 600
mcep_alpha: 0.42
mcep_dim: 25
mcep_dim_end: 28
mcep_dim_start: 2
mean_path: /world/mean
minf0: 40
num_save_intermediate_results: 4
num_workers: 2
outdir: exp/usfgan_arctic_train_16kHz_uSFGAN_60
pin_memory: true
pow_th: -20
pretrain: ''
rank: 0
remove_short_samples: true
resume: exp/usfgan_arctic_train_16kHz_uSFGAN_60/checkpoint-60000steps.pkl
sampling_rate: 16000
save_interval_steps: 5000
scale_path: /world/scale
seed: 1
shiftms: 5
source_loss_params:
  f0_ceil: 500
  f0_floor: 50
  fft_size: 1024
  hop_size: 80
  sampling_rate: 16000
stats: data/stats/arctic_train_16kHz.joblib
stats_shift: 1
stft_loss_params:
  fft_sizes:
  - 512
  - 128
  - 2048
  hop_sizes:
  - 80
  - 40
  - 640
  win_lengths:
  - 320
  - 80
  - 1920
  window: hann_window
train_audio: data/scp/arctic_train_16kHz.scp
train_feat: data/scp/arctic_train_16kHz.list
train_max_steps: 400000
uv_dim_idx: 0
valid_audio: data/scp/arctic_valid_16kHz.scp
valid_feat: data/scp/arctic_valid_16kHz.list
verbose: 1
version: 0.0.1.post1
