allow_cache: true
ap_dim_end: 39
ap_dim_start: 37
batch_max_steps: 22550
batch_size: 6
config: conf/vcc18.uSFGAN_60.yaml
discriminator_grad_norm: 1
discriminator_optimizer_params:
  eps: 1.0e-06
  lr: 5.0e-05
  weight_decay: 0.0
discriminator_params:
  bias: true
  conv_channels: 64
  in_channels: 1
  kernel_size: 3
  layers: 10
  nonlinear_activation: LeakyReLU
  nonlinear_activation_params:
    negative_slope: 0.2
  out_channels: 1
  use_weight_norm: true
discriminator_scheduler_params:
  gamma: 0.5
  step_size: 200000
discriminator_train_start_steps: 100000
discriminator_type: PWGDiscriminator
distributed: false
eval_interval_steps: 1000
f0_cont: false
f0_dim_idx: 1
feat_type: world
fft_size: 1024
generator_grad_norm: 10
generator_optimizer_params:
  eps: 1.0e-06
  lr: 0.0001
  weight_decay: 0.0
generator_params:
  aux_channels: 39
  aux_context_window: 2
  blockAs:
  - 30
  - 0
  blockFs:
  - 0
  - 30
  cascade_modes:
  - 1
  - 1
  cycleAs:
  - 6
  - 0
  cycleFs:
  - 0
  - 3
  gate_channels: 128
  hop_size: 110
  in_channels: 1
  out_channels: 1
  residual_channels: 64
  sampling_rate: 22050
  skip_channels: 64
  upsample_params:
    upsample_scales:
    - 5
    - 2
    - 11
    - 1
generator_scheduler_params:
  gamma: 0.5
  step_size: 200000
generator_type: uSFGANGenerator
highpass_cutoff: 70
hop_size: 110
lambda_adv: 4.0
lambda_source: 1.0
log_interval_steps: 100
maxf0: 800
mcep_alpha: 0.455
mcep_dim: 34
mcep_dim_end: 37
mcep_dim_start: 2
mean_path: /world/mean
minf0: 40
num_save_intermediate_results: 4
num_workers: 2
outdir: exp/usfgan_vcc18_train_22kHz_uSFGAN_60
pin_memory: true
pow_th: -20
pretrain: ''
rank: 0
remove_short_samples: true
resume: exp/usfgan_vcc18_train_22kHz_uSFGAN_60/checkpoint-Nonesteps.pkl
sampling_rate: 22050
save_interval_steps: 5000
scale_path: /world/scale
seed: 1
shiftms: 5
source_loss_params:
  f0_ceil: 450
  f0_floor: 45
  fft_size: 2048
  hop_size: 110
  sampling_rate: 22050
stats: data/stats/vcc18_train_22kHz.joblib
stats_shift: 1
stft_loss_params:
  fft_sizes:
  - 1024
  - 2048
  - 512
  hop_sizes:
  - 120
  - 240
  - 50
  win_lengths:
  - 600
  - 1200
  - 240
  window: hann_window
train_audio: data/scp/vcc18_train_22kHz.scp
train_feat: data/scp/vcc18_train_22kHz.list
train_max_steps: 400000
uv_dim_idx: 0
valid_audio: data/scp/vcc18_valid_22kHz.scp
valid_feat: data/scp/vcc18_valid_22kHz.list
verbose: 1
version: 0.0.1.post1
